import type { MenuItem, ToolbarItem } from '../model';

export const axes = ['X', 'Y', 'Z'] as const;
export const coordinateSystems = [
  'G54',
  'G55',
  'G56',
  'G57',
  'G58',
  'G59',
  'G59.1',
  'G59.2',
  'G59.3',
];
const separator = (id: string): MenuItem => ({ id, label: '', kind: 'separator' });
const command = (id: string, label: string, shortcut?: string): MenuItem => ({
  id,
  label,
  shortcut,
});
const check = (id: string, label: string, shortcut?: string): MenuItem => ({
  id,
  label,
  shortcut,
  kind: 'check',
});
const radio = (group: string, value: string, label: string, shortcut?: string): MenuItem => ({
  id: `${group}.${value}`,
  label,
  shortcut,
  kind: 'radio',
  group,
  value,
});

export const menus: MenuItem[] = [
  {
    id: 'file',
    label: 'File',
    children: [
      command('file.open', 'Open…', 'O'),
      {
        id: 'file.recent',
        label: 'Recent Files',
        children: [
          command('file.open-sample', 'axis.ngc'),
          separator('file.recent-s1'),
          command('file.clear-recents', 'Clear Recents List'),
        ],
      },
      command('file.edit', 'Edit…'),
      command('file.reload', 'Reload', 'Ctrl-R'),
      command('file.save', 'Save G-code as…', 'Ctrl-S'),
      command('file.properties', 'Properties…'),
      separator('file.s1'),
      command('tool.edit', 'Edit tool data…'),
      command('tool.reload', 'Reload tool data'),
      separator('file.s2'),
      command('machine.ladder', 'Ladder Editor…'),
      separator('file.s3'),
      command('file.quit', 'Quit'),
    ],
  },
  {
    id: 'machine',
    label: 'Machine',
    children: [
      command('machine.estop', 'Toggle Emergency Stop', 'F1'),
      command('machine.power', 'Toggle Machine Power', 'F2'),
      separator('machine.s1'),
      command('program.run', 'Run program', 'R'),
      command('program.run-line', 'Run from selected line'),
      command('program.step', 'Step', 'T'),
      command('program.pause', 'Pause', 'P'),
      command('program.resume', 'Resume', 'S'),
      command('program.stop', 'Stop', 'Esc'),
      check('program.optional', 'Stop at M1'),
      check('program.block-delete', "Skip lines with '/'"),
      separator('machine.s2'),
      command('mdi.clear', 'Clear MDI history', 'Ctrl-M'),
      command('mdi.copy', 'Copy from MDI history', 'Ctrl-H'),
      command('mdi.paste', 'Paste to MDI history', 'Ctrl-Shift-H'),
      separator('machine.s3'),
      command('machine.calibration', 'Calibration'),
      command('machine.hal-config', 'Show Hal Configuration'),
      command('machine.hal-meter', 'Hal Meter'),
      command('machine.hal-scope', 'Hal Scope'),
      command('machine.status', 'Show LinuxCNC Status'),
      command('machine.debug', 'Set Debug Level'),
      separator('machine.s4'),
      {
        id: 'machine.homing',
        label: 'Homing',
        children: [
          command('machine.home-all', 'Home All Axes'),
          ...axes.map((axis) => command(`machine.home-${axis}`, `Home Axis ${axis}`)),
        ],
      },
      {
        id: 'machine.unhoming',
        label: 'Unhoming',
        children: [
          command('machine.unhome-all', 'Unhome All Axes'),
          ...axes.map((axis) => command(`machine.unhome-${axis}`, `Unhome Axis ${axis}`)),
        ],
      },
      {
        id: 'machine.zero',
        label: 'Zero coordinate system',
        children: [
          ...coordinateSystems.map((system, index) =>
            command(`machine.zero-${system}`, `P${index + 1} ${system}`),
          ),
          command('machine.zero-G92', 'G92'),
        ],
      },
      separator('machine.s5'),
      radio('touch', 'workpiece', 'Tool touch off to workpiece'),
      radio('touch', 'fixture', 'Tool touch off to fixture'),
    ],
  },
  {
    id: 'view',
    label: 'View',
    children: [
      radio('view', 'z', 'Top view', 'V'),
      radio('view', 'z2', 'Rotated Top view', 'V'),
      radio('view', 'x', 'Side view', 'V'),
      radio('view', 'y', 'Front view', 'V'),
      radio('view', 'p', 'Perspective view', 'V'),
      separator('view.s1'),
      radio('units', 'inch', 'Display Inches', '!'),
      radio('units', 'mm', 'Display MM', '!'),
      separator('view.s2'),
      check('show.program', 'Show program'),
      check('show.rapids', 'Show program rapids'),
      check('show.alpha', 'Alpha-blend program'),
      check('show.live', 'Show live plot'),
      check('show.tool', 'Show tool'),
      check('show.extents', 'Show extents'),
      {
        id: 'view.grid',
        label: 'Grid',
        children: [
          radio('grid', 'off', 'Off'),
          command('view.grid-custom', 'Custom'),
          ...['10mm', '20mm', '50mm', '100mm', '1in', '2in', '5in', '10in'].map((size) =>
            radio('grid', size, size),
          ),
        ],
      },
      check('show.offsets', 'Show offsets'),
      check('show.limits', 'Show machine limits'),
      check('show.velocity', 'Show velocity'),
      check('show.dtg', 'Show distance to go'),
      check('show.large', 'Large coordinate font'),
      command('view.clear', 'Clear live plot', 'Ctrl-K'),
      check('show.pyvcp', 'Show PyVCP panel', 'Ctrl-E'),
      separator('view.s3'),
      radio('position', 'commanded', 'Show commanded position', '@'),
      radio('position', 'actual', 'Show actual position', '@'),
      separator('view.s4'),
      radio('coordinates', 'machine', 'Show machine position', '#'),
      radio('coordinates', 'relative', 'Show relative position', '#'),
      separator('view.s5'),
      radio('mode', 'joint', 'Joint mode', '$'),
      radio('mode', 'world', 'World mode', '$'),
    ],
  },
  {
    id: 'help',
    label: 'Help',
    children: [command('help.about', 'About AXIS'), command('help.reference', 'Quick Reference')],
  },
];

export const toolbar: ToolbarItem[] = [
  { id: 'machine.estop', label: 'Toggle Emergency Stop [F1]', icon: 'tool_estop' },
  { id: 'machine.power', label: 'Toggle Machine power [F2]', icon: 'tool_power' },
  { id: 'file.open', label: 'Open G-Code file [O]', icon: 'tool_open', separator: true },
  { id: 'file.reload', label: 'Reopen current file [Ctrl-R]', icon: 'tool_reload' },
  {
    id: 'program.run',
    label: 'Begin executing current file [R]',
    icon: 'tool_run',
    separator: true,
  },
  { id: 'program.step', label: 'Execute next line [T]', icon: 'tool_step' },
  { id: 'program.pause', label: 'Pause [P] / resume [S] execution', icon: 'tool_pause' },
  { id: 'program.stop', label: 'Stop program execution [Esc]', icon: 'tool_stop' },
  {
    id: 'program.block-delete',
    label: "Toggle skip lines with '/' [Alt-M /]",
    icon: 'tool_blockdelete',
    separator: true,
  },
  { id: 'program.optional', label: 'Toggle optional pause [Alt-M 1]', icon: 'tool_optpause' },
  { id: 'view.zoom-in', label: 'Zoom in', icon: 'tool_zoomin', separator: true },
  { id: 'view.zoom-out', label: 'Zoom out', icon: 'tool_zoomout' },
  { id: 'view.z', label: 'Top view', icon: 'tool_axis_z' },
  { id: 'view.z2', label: 'Rotated Top view', icon: 'tool_axis_z2' },
  { id: 'view.x', label: 'Side view', icon: 'tool_axis_x' },
  { id: 'view.y', label: 'Front view', icon: 'tool_axis_y' },
  { id: 'view.p', label: 'Perspective view', icon: 'tool_axis_p' },
  { id: 'view.rotate', label: 'Toggle between Drag and Rotate Mode [D]', icon: 'tool_rotate' },
  { id: 'view.clear', label: 'Clear live plot [Ctrl-K]', icon: 'tool_clear', separator: true },
];

export const quickReference = [
  ['F1', 'Emergency stop'],
  ['F2', 'Machine power'],
  ['F3', 'Manual control'],
  ['F5', 'MDI'],
  ['O', 'Open a file'],
  ['Ctrl-R', 'Reload file'],
  ['R / T', 'Run / step program'],
  ['P / S', 'Pause / resume'],
  ['Esc', 'Stop'],
  ['X / Y / Z', 'Select axis'],
  ['← → / ↑ ↓ / PgUp PgDn', 'Jog X / Y / Z'],
  ['Home', 'Home selected axis'],
  ['End', 'Touch off'],
  ['V', 'Cycle views'],
  ['D', 'Drag / rotate'],
  ['Ctrl-K', 'Clear live plot'],
  ['! / @ / #', 'Units / position feedback / coordinates'],
];
