import type { MenuItem, ToolbarItem } from '../model';

export const axes = ['X', 'Y', 'Z'] as const;
export const coordinateSystems = [
  'G54',
  'G55',
  'G56',
  'G57',
  'G58',
  'G59',
  'G59.1',
  'G59.2',
  'G59.3',
];
const separator = (id: string): MenuItem => ({ id, label: '', kind: 'separator' });
const command = (id: string, label: string, shortcut?: string): MenuItem => ({
  id,
  label,
  shortcut,
});
const check = (id: string, label: string, shortcut?: string): MenuItem => ({
  id,
  label,
  shortcut,
  kind: 'check',
});
const radio = (group: string, value: string, label: string, shortcut?: string): MenuItem => ({
  id: `${group}.${value}`,
  label,
  shortcut,
  kind: 'radio',
  group,
  value,
});

export const menus: MenuItem[] = [
  {
    id: 'file',
    label: '文件',
    children: [
      command('file.open', '打开程序…', 'O'),
      {
        id: 'file.recent',
        label: '最近打开',
        children: [
          command('file.open-sample', 'axis.ngc'),
          separator('file.recent-s1'),
          command('file.clear-recents', '清空最近打开记录'),
        ],
      },
      command('file.edit', '编辑程序…'),
      command('file.reload', '重新加载', 'Ctrl+R'),
      command('file.save', '程序另存为…', 'Ctrl+S'),
      command('file.properties', '程序属性…'),
      separator('file.s1'),
      command('tool.edit', '编辑刀具表…'),
      command('tool.reload', '重新加载刀具表'),
      separator('file.s2'),
      command('machine.ladder', '梯形图编辑器…'),
      separator('file.s3'),
      command('file.quit', '退出'),
    ],
  },
  {
    id: 'machine',
    label: '机床',
    children: [
      command('machine.estop', '切换急停状态', 'F1'),
      command('machine.power', '机床使能／关闭', 'F2'),
      separator('machine.s1'),
      command('program.run', '运行程序', 'R'),
      command('program.run-line', '从选中行运行'),
      command('program.step', '单段运行', 'T'),
      command('program.pause', '暂停运行', 'P'),
      command('program.resume', '继续运行', 'S'),
      command('program.stop', '停止运行', 'Esc'),
      check('program.optional', '选择停（M1）'),
      check('program.block-delete', '程序段跳过（/）'),
      separator('machine.s2'),
      command('mdi.clear', '清空手动输入历史', 'Ctrl+M'),
      command('mdi.copy', '复制历史指令', 'Ctrl+H'),
      command('mdi.paste', '粘贴到历史指令', 'Ctrl+Shift+H'),
      separator('machine.s3'),
      command('machine.calibration', '参数校准'),
      command('machine.hal-config', '查看 HAL 配置'),
      command('machine.hal-meter', 'HAL 信号监视'),
      command('machine.hal-scope', 'HAL 示波器'),
      command('machine.status', '查看控制器状态'),
      command('machine.debug', '设置调试级别'),
      separator('machine.s4'),
      {
        id: 'machine.homing',
        label: '回零',
        children: [
          command('machine.home-all', '全部轴回零'),
          ...axes.map((axis) => command(`machine.home-${axis}`, `${axis} 轴回零`)),
        ],
      },
      {
        id: 'machine.unhoming',
        label: '清除回零状态',
        children: [
          command('machine.unhome-all', '清除全部轴回零状态'),
          ...axes.map((axis) => command(`machine.unhome-${axis}`, `清除 ${axis} 轴回零状态`)),
        ],
      },
      {
        id: 'machine.zero',
        label: '清除坐标系偏置',
        children: [
          ...coordinateSystems.map((system, index) =>
            command(`machine.zero-${system}`, `${system} 工件坐标系（P${index + 1}）`),
          ),
          command('machine.zero-G92', 'G92 临时坐标偏置'),
        ],
      },
      separator('machine.s5'),
      radio('touch', 'workpiece', '以工件为对刀基准'),
      radio('touch', 'fixture', '以夹具为对刀基准'),
    ],
  },
  {
    id: 'view',
    label: '视图',
    children: [
      radio('view', 'z', '俯视图', 'V'),
      radio('view', 'z2', '旋转俯视图', 'V'),
      radio('view', 'x', '侧视图', 'V'),
      radio('view', 'y', '正视图', 'V'),
      radio('view', 'p', '透视图', 'V'),
      separator('view.s1'),
      radio('units', 'inch', '使用英寸显示', '!'),
      radio('units', 'mm', '使用毫米显示', '!'),
      separator('view.s2'),
      check('show.program', '显示程序刀路'),
      check('show.rapids', '显示快速移动轨迹'),
      check('show.alpha', '半透明显示刀路'),
      check('show.live', '显示实际运动轨迹'),
      check('show.tool', '显示刀具'),
      check('show.extents', '显示加工范围'),
      {
        id: 'view.grid',
        label: '网格',
        children: [
          radio('grid', 'off', '隐藏网格'),
          command('view.grid-custom', '自定义间距…'),
          ...['10mm', '20mm', '50mm', '100mm', '1in', '2in', '5in', '10in'].map((size) =>
            radio('grid', size, size.replace('mm', ' 毫米').replace('in', ' 英寸')),
          ),
        ],
      },
      check('show.offsets', '显示坐标偏置'),
      check('show.limits', '显示机床行程范围'),
      check('show.velocity', '显示当前速度'),
      check('show.dtg', '显示剩余行程'),
      check('show.large', '放大坐标字体'),
      command('view.clear', '清除实际运动轨迹', 'Ctrl+K'),
      check('show.pyvcp', '显示自定义面板（PyVCP）', 'Ctrl+E'),
      separator('view.s3'),
      radio('position', 'commanded', '显示指令位置', '@'),
      radio('position', 'actual', '显示实际位置', '@'),
      separator('view.s4'),
      radio('coordinates', 'machine', '显示机床坐标', '#'),
      radio('coordinates', 'relative', '显示工件坐标', '#'),
      separator('view.s5'),
      radio('mode', 'joint', '关节模式', '$'),
      radio('mode', 'world', '坐标轴模式', '$'),
    ],
  },
  {
    id: 'help',
    label: '帮助',
    children: [command('help.about', '关于本界面'), command('help.reference', '快捷键说明')],
  },
];

export const toolbar: ToolbarItem[] = [
  { id: 'machine.estop', label: '切换急停状态 [F1]', icon: 'tool_estop' },
  { id: 'machine.power', label: '机床使能／关闭 [F2]', icon: 'tool_power' },
  { id: 'file.open', label: '打开加工程序 [O]', icon: 'tool_open', separator: true },
  { id: 'file.reload', label: '重新加载当前程序 [Ctrl+R]', icon: 'tool_reload' },
  {
    id: 'program.run',
    label: '运行当前程序 [R]',
    icon: 'tool_run',
    separator: true,
  },
  { id: 'program.step', label: '单段运行 [T]', icon: 'tool_step' },
  { id: 'program.pause', label: '暂停 [P]／继续运行 [S]', icon: 'tool_pause' },
  { id: 'program.stop', label: '停止程序 [Esc]', icon: 'tool_stop' },
  {
    id: 'program.block-delete',
    label: '程序段跳过（/）',
    icon: 'tool_blockdelete',
    separator: true,
  },
  { id: 'program.optional', label: '选择停（M1）', icon: 'tool_optpause' },
  { id: 'view.zoom-in', label: '放大', icon: 'tool_zoomin', separator: true },
  { id: 'view.zoom-out', label: '缩小', icon: 'tool_zoomout' },
  { id: 'view.z', label: '俯视图', icon: 'tool_axis_z' },
  { id: 'view.z2', label: '旋转俯视图', icon: 'tool_axis_z2' },
  { id: 'view.x', label: '侧视图', icon: 'tool_axis_x' },
  { id: 'view.y', label: '正视图', icon: 'tool_axis_y' },
  { id: 'view.p', label: '透视图', icon: 'tool_axis_p' },
  { id: 'view.rotate', label: '切换平移／旋转视图 [D]', icon: 'tool_rotate' },
  { id: 'view.clear', label: '清除实际运动轨迹 [Ctrl+K]', icon: 'tool_clear', separator: true },
];

export const quickReference = [
  ['F1', '急停'],
  ['F2', '机床使能／关闭'],
  ['F3', '手动操作'],
  ['F5', '手动输入指令'],
  ['O', '打开程序'],
  ['Ctrl+R', '重新加载程序'],
  ['R / T', '运行程序／单段运行'],
  ['P / S', '暂停／继续运行'],
  ['Esc', '停止运行'],
  ['X / Y / Z', '选择坐标轴'],
  ['← → / ↑ ↓ / PgUp PgDn', 'X／Y／Z 轴点动'],
  ['Home', '选中轴回零'],
  ['End', '工件对刀'],
  ['V', '切换视图'],
  ['D', '平移／旋转视图'],
  ['Ctrl+K', '清除实际运动轨迹'],
  ['! / @ / #', '切换单位／位置类型／坐标系'],
];
